version: '3.8'
services:
  pgadmin4:
      image: elestio/pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: leandropoletti@outlook.com
        PGADMIN_DEFAULT_PASSWORD: Senha123
        PGADMIN_LISTEN_PORT: 8080
      ports:
      - "8080:8080"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  simulator:
    build: ./simulator
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - SIM_TIME_RATIO=60 # 1s = 60 simulated seconds (configurable)
      - OCCUPIED_HOLD_SEC=60
    depends_on:
      - mosquitto
    ports:
      - "3000:3000" # HTTP control

  backend:
    build: ./backend
    environment:
      - ConnectionStrings__Default=Host=postgres;Database=parking;Username=parking_user;Password=parking_pass;Include Error Detail=true
      - ASPNETCORE_URLS=http://+:80
      - STUCK_SECONDS=30
      - OCCUPIED_HOLD_SEC=60
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - postgres
      - mosquitto
    ports:
      - "5000:80"

volumes:
  pgdata:
