listener 1883
protocol mqtt

# allow anonymous for demo only
allow_anonymous true

# websocket for test UI
listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/
log_type all
